zoom_store:
    resource: "@ZoomStoreBundle/Resources/config/routing.yml"

zoom_user:
    resource: "@ZoomUserBundle/Resources/config/routing.yml"

zoom_douala:
    resource: "@ZoomDoualaBundle/Resources/config/routing.yml"

fos_user_security:
    resource: "@FOSUserBundle/Resources/config/routing/security.xml"

fos_user_profile:
    resource: "@FOSUserBundle/Resources/config/routing/profile.xml"
    prefix: /{_locale}/profile
    requirements:
        _locale: en|fr|cn|es|ar

fos_user_registration_register:
    resource: "@FOSUserBundle/Resources/config/routing/registration.xml"
    prefix: /{_locale}/register
    requirements:
        _locale: en|fr|cn|es|ar

fos_user_resetting:
    resource: "@FOSUserBundle/Resources/config/routing/resetting.xml"
    prefix: /{_locale}/resetting
    requirements:
        _locale: en|fr|cn|es|ar

fos_user_change_password:
    resource: "@FOSUserBundle/Resources/config/routing/change_password.xml"
    prefix: /{_locale}/profile
    requirements:
        _locale: en|fr|cn|es|ar

login:
    path: /{_locale}/login
    defaults:  { _controller: ZoomUserBundle:Security:login }
    requirements:
        _locale: en|fr|cn|es|ar

login_check:
    path: /{_locale}/login_check
    requirements:
        _locale: en|fr|cn|es|ar

logout:
    path: /{_locale}/logout
    requirements:
        _locale: en|fr|cn|es|ar

admin_login:
    path: /{_locale}/admin/login
    defaults:  { _controller: ZoomUserBundle:Security:login }
    requirements:
        _locale: en|fr|cn|es|ar

admin_login_check:
    path: /{_locale}/admin/login_check
    requirements:
        _locale: en|fr|cn|es|ar

admin_logout:
    path: /{_locale}/admin/logout
    requirements:
        _locale: en|fr|cn|es|ar