security:

    session_fixation_strategy: migrate

    role_hierarchy:
        ROLE_ADMIN:       ROLE_USER
        ROLE_SUPER_ADMIN: ROLE_ADMIN

    providers:
        fos_userbundle:
            id: fos_user.user_provider.username
        in_memory:
            memory:
                users:
                    admin:
                        password: 64y8s=S2
                        roles: 'ROLE_SUPER_ADMIN'
    encoders:
        Symfony\Component\Security\Core\User\User: plaintext
        Zoom\UserBundle\Entity\User: sha512

    firewalls:
        admin:
            pattern:   /admin/(.*)
            form_login:
                provider:  in_memory
                login_path: admin_login
                check_path: admin_login_check
                default_target_path: /admin/activite/lister
            logout:
                path:   admin_logout
                target: admin_login
            anonymous:  true
            context:    application

        user:
            pattern: ^/
            anonymous: true
            form_login:
                provider: fos_userbundle
                csrf_token_generator: security.csrf.token_manager
                login_path: login
                check_path: login_check
                default_target_path: /%locale%/store/companyregistration/list
            logout:
                path:   logout
                target: login
            context:    application

    access_control:
        - { path: ^/admin/login$, role: IS_AUTHENTICATED_ANONYMOUSLY }
        - { path: ^/login$, role: IS_AUTHENTICATED_ANONYMOUSLY }
        - { path: ^/admin/logout$, role: IS_AUTHENTICATED_ANONYMOUSLY }
        - { path: ^/logout$, role: IS_AUTHENTICATED_ANONYMOUSLY }
        - { path: ^/admin, role: ROLE_SUPER_ADMIN }
        - { path: ^/register$, role: IS_AUTHENTICATED_ANONYMOUSLY }
        - { path: ^/(en|fr|es|ar|cn)/store/showcase$, role: IS_AUTHENTICATED_ANONYMOUSLY }
        - { path: ^/(en|fr|es|ar|cn)/store/checkout, role: ROLE_USER }
        - { path: ^/(en|fr|es|ar|cn)/store/myads, role: ROLE_USER }
        - { path: ^/(en|fr|es|ar|cn)/store/mypage, role: ROLE_USER }
        - { path: ^/(en|fr|es|ar|cn)/store/companyrep, role: ROLE_USER }
        - { path: ^/(en|fr|es|ar|cn)/store/companyalaune, role: ROLE_USER }
        - { path: ^/(en|fr|es|ar|cn)/store/companyregistration, role: ROLE_USER }
        - { path: ^/(en|fr|es|ar|cn)/store/myimage/image, role: ROLE_USER }